// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlagiTracker.Data.DataAccess;

#nullable disable

namespace PlagiTracker.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260603150333_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("plagi_tracker")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlagiTracker.Data.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DolosURLId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsAnalyzed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId", "Title")
                        .IsUnique();

                    b.ToTable("Assignments", "plagi_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ac85b4e5-33ea-4d2c-a281-f7ec41da15f7"),
                            AnalysisDate = new DateTime(2024, 10, 9, 23, 40, 4, 711, DateTimeKind.Utc).AddTicks(5580),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 18, 0, 46, 30, 389, DateTimeKind.Utc),
                            Description = "",
                            IsAnalyzed = true,
                            IsEnabled = true,
                            SubmissionDate = new DateTime(2024, 12, 7, 15, 14, 26, 713, DateTimeKind.Utc),
                            Title = "Programación Orientada a Objetos",
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e4be8d12-8d5e-43d2-817c-b5997043304d"),
                            AnalysisDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 18, 0, 46, 30, 389, DateTimeKind.Utc).AddTicks(3520),
                            Description = "Ninguna",
                            IsAnalyzed = false,
                            IsEnabled = true,
                            SubmissionDate = new DateTime(2024, 12, 25, 0, 43, 58, 850, DateTimeKind.Utc),
                            Title = "Programación Orientada a Objetos 2",
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("025f1811-79ec-43b2-9693-652fa2f7bdb1"),
                            AnalysisDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 18, 0, 48, 36, 691, DateTimeKind.Utc).AddTicks(7520),
                            DolosURLId = "8299776248912629284",
                            IsAnalyzed = false,
                            IsEnabled = true,
                            SubmissionDate = new DateTime(2024, 12, 25, 0, 43, 58, 850, DateTimeKind.Utc),
                            Title = "Programación Orientada a Objetos 3",
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e4be8d12-8d5e-43d2-817c-b5987043404d"),
                            AnalysisDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 18, 0, 46, 30, 389, DateTimeKind.Utc),
                            Description = "Ninguna",
                            DolosURLId = "3950420146690480254",
                            IsAnalyzed = false,
                            IsEnabled = true,
                            SubmissionDate = new DateTime(2024, 12, 25, 0, 43, 58, 850, DateTimeKind.Utc),
                            Title = "Cylinder",
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ParentClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentClassId");

                    b.HasIndex("ExerciseId", "Name")
                        .IsUnique();

                    b.ToTable("Classes", "plagi_tracker");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Code", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId", "FileName")
                        .IsUnique();

                    b.ToTable("Codes", "plagi_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0eeb1d1-9e34-4157-9744-b9ee629a61c2"),
                            Content = "public class Main\n{\n    public static void main(String[] args) {\n        System.out.println(\"Hello PlagiTracker\");\n    }\n}",
                            CreatedAt = new DateTime(2024, 11, 18, 0, 27, 48, 334, DateTimeKind.Utc).AddTicks(2680),
                            FileName = "Main.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("7d0f9c15-9e1b-4301-8b6e-7812cca1d451"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a7b61980-fb3c-46b6-8471-46c7c80b55fd"),
                            Content = "public class Person {\n    private String name;\n    private int age;\n\n    public Person(String name, int age) {\n        this.name = name;\n        this.age = age;\n    }\n\n    public String getName() {\n        return name;\n    }\n\n    public int getAge() {\n        return age;\n    }\n\n    public void setName(String name) {\n        this.name = name;\n    }\n",
                            CreatedAt = new DateTime(2024, 11, 18, 0, 27, 48, 358, DateTimeKind.Utc).AddTicks(4480),
                            FileName = "Person.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("7d0f9c15-9e1b-4301-8b6e-7812cca1d451"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bab848e0-1ce8-4d0f-83b4-8b95afda5047"),
                            Content = "public class Main\n{\n    public static void main(String[] args) {\n\n        // con esto imprimo\n        System.out.println(\"Hello My Friend!\");\n    }\n}",
                            CreatedAt = new DateTime(2024, 11, 18, 1, 28, 57, 764, DateTimeKind.Utc).AddTicks(3200),
                            FileName = "Main.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("7397a9ce-94a9-4e5b-9cbb-215f061b197e"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("09b35d8c-a153-4a9a-a218-84a379fe868c"),
                            Content = "public class Persona {\n    private String nombre;\n    int edad;\n\n    public Persona(String name, int age) {\n        this.nombre = name;\n        this.edad = age;\n    }\n\n    public String getName() {\n        return nombre;\n    }\n\n    public int getAge() {\n        return edad;\n    }\n\n    public void setName(String name) {\n        this.nombre = name;\n    }\n\n    public void setAge(int age) {\n        this.edad = age;\n    }\n}",
                            CreatedAt = new DateTime(2024, 11, 18, 1, 28, 57, 782, DateTimeKind.Utc).AddTicks(5380),
                            FileName = "Persona.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("7397a9ce-94a9-4e5b-9cbb-215f061b197e"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("83bafa2e-f925-4ab5-a1d7-be8d030eb0b9"),
                            Content = "public class Main\n{\n    public static void main(String[] args) {\n        System.out.println(\"Hello PlagiTracker\");\n    }\n}",
                            CreatedAt = new DateTime(2024, 11, 18, 14, 36, 13, 451, DateTimeKind.Utc).AddTicks(9740),
                            FileName = "Main.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("14cabe76-3398-4429-ad34-01679f08acb9"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a3c6fd63-81e7-4bca-8a49-b163f292400b"),
                            Content = "public class Person\n{\n    private String fname;\n    private String lname;\n    private int age;\n\n\n    public String getFname()\n    {\n        return fname;\n    }\n\n\n    public String getLname()\n    {\n        return lname;\n    }\n\n\n    public int getAge()\n    {\n        return age;\n    }\n\n\n    ",
                            CreatedAt = new DateTime(2024, 11, 18, 14, 36, 13, 473, DateTimeKind.Utc).AddTicks(2670),
                            FileName = "Person.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("14cabe76-3398-4429-ad34-01679f08acb9"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("4abb984e-aead-4b40-88b0-8c801fdde54c"),
                            Content = "\npackage com.example;\n\nclass HelloCodiva {\n    public static void main(String[] args) {\n        int a = 15;\n        int b = 20; // will generate an error\n        int c = 654;\n        System.out.println(a+b+c);\n    }\n}\n",
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "HelloCodiva.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("31edb16a-feb4-4cab-812c-e8a4bdb6ad45"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("5c96bfec-28ba-4c23-b9da-fbf4cf835e0d"),
                            Content = "\npackage com.example;\n\npublic class Main {\n    public static void main(String[] args) {\n        int myNum = 5;\n        float myFloatNum = 5.99f;\n        char myLetter = 'D';\n        boolean myBool = true;\n        String myText = \"Hello\";\n        System.out.println(myNum);\n        System.out.println(myFloatNum);\n        System.out.println(myLetter);\n        System.out.println(myBool);\n        System.out.println(myText);\n    }\n}",
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Main.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("31edb16a-feb4-4cab-812c-e8a4bdb6ad45"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("301e8585-ac92-4bd2-809b-262228bcc1c1"),
                            Content = "package com.example;\n\nclass HelloCodiva {\n\n    public static void main(String[] args) {\n\n        String greeting = \"Hello World\";\n        System.out.println(greeting);\n\n    }\n}\n",
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "HelloCodiva.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("e0d30fd2-1027-4af3-be3b-238a579dacb8"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("32914a3b-9b54-4e6b-ad27-033693f8e181"),
                            Content = "\npackage com.example;\n\nclass Main {\n    public static void main(String[] args) {\n        char myLetter = 'D';\n        boolean myBool = true;\n        String myText = \"Hello\";\n\n        int myNum = 5;\n        float myFloatNum = 5.99f;\n\n        System.out.println(myNum);\n        System.out.println(myFloatNum);\n        System.out.println(myLetter);\n        System.out.println(myBool);\n        System.out.println(myText);\n    }\n}",
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            FileName = "Main.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("e0d30fd2-1027-4af3-be3b-238a579dacb8"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c939bfb1-7324-4715-9f85-cd8c3cb99035"),
                            Content = "package E_1_first_exercise;\n\npublic class First_exercise {\n    public static void main(String args[]){\n\n        int number_1 = 8;\n        int number_2 = 15;\n\n        number_1 = number_1 + number_2;\n        number_2 = number_1 - number_2;\n        number_1 = number_1 - number_2;\n\n        System.out.println(\"First: \" + number_1);\n        System.out.println(\"Second: \" + number_2);\n\n        System.out.println(\"Doston Hamrakulov doston.hamrakulov@gmail.com\");\n    }\n}\n",
                            CreatedAt = new DateTime(2024, 11, 18, 18, 3, 59, 319, DateTimeKind.Utc).AddTicks(420),
                            FileName = "First_exercise.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("fe8eb5ea-7686-4539-b13b-51bf931d36bb"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c9281571-e24b-4c92-875b-b59e5ae88fdf"),
                            Content = "\nimport java.util.Scanner;\n\npublic class nCylinder {\n    public static void main(String[] args){\n\n        Scanner sc = new Scanner(System.in);\n\n        System.out.print(\"Enter the radius and length of a cylinder: \");\n        double radius = sc.nextDouble();\n        double length = sc.nextDouble();\n\n        double area = radius * radius * 3.14159;\n        double volume = area * length;\n\n        System.out.println(\"The area is \" + (float)area);\n        System.out.printf(\"The volume is %.1f\", volume);\n        System.out.println();\n\n    }\n}\n",
                            CreatedAt = new DateTime(2024, 11, 18, 18, 31, 7, 7, DateTimeKind.Utc).AddTicks(5070),
                            FileName = "nCylinder.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("d00b5731-977d-41cf-b8bf-7f693cb8d97b"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7996e30e-e7c0-4c5a-baa7-dd50faa3a3eb"),
                            Content = "\nimport java.util.Scanner;\n\npublic class ncylinder {\n\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        System.out.print(\"Enter the radius and length of a cylinder : \");\n        double radius = sc.nextDouble();\n        double length = sc.nextDouble();\n        double area = (radius * radius) * 3.14159;\n        double volume = area * length;\n        System.out.println(\"The area is : \" + area);\n        System.out.println(\"The volume is : \" + volume);\n    }\n\n}\n",
                            CreatedAt = new DateTime(2024, 11, 18, 18, 36, 44, 138, DateTimeKind.Utc).AddTicks(510),
                            FileName = "ncylinder.java",
                            IsEnabled = true,
                            SubmissionId = new Guid("22e13d14-0349-49df-9fc9-ff6c9bbb4bd8"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitationId")
                        .IsRequired()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvitationId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses", "plagi_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Programming Language I",
                            TeacherId = new Guid("0392d24c-a1f5-4022-8278-cfa4efb14b8c"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("bf9ee4c7-b051-4dd8-ba56-101f2688888c"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("bf9ee4c7-b051-4dd8-ba56-101f2688888c"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Introduction to Programming",
                            TeacherId = new Guid("0392d24c-a1f5-4022-8278-cfa4efb14b8c"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a1"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a2"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Programming Language II",
                            TeacherId = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a3"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a4"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Programming Language III",
                            TeacherId = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a5"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a6"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Data Structure I",
                            TeacherId = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a7"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a8"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Data Structure II",
                            TeacherId = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e88a9"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("aa597a6c-b219-4743-b5c6-8740551e88e0"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Analysis and Design of Algorithms I",
                            TeacherId = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e88b1"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("aa597a6c-b219-4743-b5c6-8740551e88b1"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Analysis and Design of Algorithms II",
                            TeacherId = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e88b2"),
                            CreatedAt = new DateTime(2024, 10, 10, 15, 10, 10, 100, DateTimeKind.Utc),
                            InvitationId = new Guid("aa597a6c-b219-4743-b5c6-8740551e88d2"),
                            IsArchived = false,
                            IsEnabled = true,
                            Name = "Fundamentals of Programming Languages",
                            TeacherId = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Grade")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments", "plagi_tracker");

                    b.HasData(
                        new
                        {
                            StudentId = new Guid("38141a4f-bc22-4514-8f9b-139a11b004b8"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 6, 4, 8, 45, 690, DateTimeKind.Utc).AddTicks(1410),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("38141a4f-bc22-4514-8f9b-139a11b004b2"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 6, 4, 56, 54, 940, DateTimeKind.Utc).AddTicks(6620),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("a37b3252-3e54-4199-8c4b-728238fc76b8"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 6, 4, 59, 6, 498, DateTimeKind.Utc).AddTicks(9810),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("8d676dc9-1a50-48f6-aa83-cb47535c5af3"),
                            CourseId = new Guid("bf9ee4c7-b051-4dd8-ba56-101f2688888c"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 49, 21, 232, DateTimeKind.Utc).AddTicks(9780),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("8d676dc9-1a50-48f6-aa83-cb47535c5af3"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 59, 31, 81, DateTimeKind.Utc).AddTicks(3270),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("38141a4f-bc22-4514-8f9b-139a11b004b8"),
                            CourseId = new Guid("bf9ee4c7-b051-4dd8-ba56-101f2688888c"),
                            CreatedAt = new DateTime(2024, 11, 6, 4, 8, 40, 787, DateTimeKind.Utc).AddTicks(8820),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("1979d2a7-de35-4d83-9aa9-857171cba7fa"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 59, 31, 81, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("12bedd1a-d7c6-4b54-aeb5-507ef12d4f83"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 59, 31, 81, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("239e66d0-16c3-4ce4-b321-058b64269f5e"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 59, 31, 81, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("9b934e06-3abd-4b8d-b45f-7e2106b4bc74"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 59, 31, 81, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("af2eff91-54b0-43b4-91c4-57b7e2d62f15"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 59, 31, 81, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            StudentId = new Guid("e7c43279-2bcc-4c09-9165-b824041166fc"),
                            CourseId = new Guid("5500125e-16f5-4b77-9220-cc4dab69c100"),
                            CreatedAt = new DateTime(2024, 11, 17, 12, 59, 31, 81, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HaveBody")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId", "Name")
                        .IsUnique();

                    b.ToTable("Exercises", "plagi_tracker");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Method", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ParameterTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClassId", "Type", "Name", "ParameterTypes")
                        .IsUnique();

                    b.ToTable("Methods", "plagi_tracker");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("MethodId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MethodId", "Type", "Name")
                        .IsUnique();

                    b.ToTable("Parameter", "plagi_tracker");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Plagiarism", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Algorithm")
                        .HasColumnType("integer");

                    b.Property<Guid>("CodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodeSnippet")
                        .HasColumnType("text");

                    b.Property<int>("Coincidences")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<double>("Similarity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeId");

                    b.HasIndex("Id", "CodeId", "Algorithm")
                        .IsUnique();

                    b.ToTable("Plagiarisms", "plagi_tracker");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Compiler")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Grade")
                        .HasColumnType("decimal(4, 2)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<int>("UrlState")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("StudentId", "AssignmentId", "Url")
                        .IsUnique();

                    b.ToTable("Submissions", "plagi_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e701991-2a14-4493-a170-f4fe910e9c4a"),
                            AssignmentId = new Guid("ac85b4e5-33ea-4d2c-a281-f7ec41da15f7"),
                            Compiler = 0,
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("12bedd1a-d7c6-4b54-aeb5-507ef12d4f83"),
                            SubmissionDate = new DateTime(2024, 10, 7, 15, 5, 31, 51, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.codiva.io/p/9f4e0e63-82d0-4241-b0bf-e12ae7a9b700",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("b6c2d5e1-33c4-4048-820b-03d25fe674b9"),
                            AssignmentId = new Guid("ac85b4e5-33ea-4d2c-a281-f7ec41da15f7"),
                            Compiler = 0,
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("af2eff91-54b0-43b4-91c4-57b7e2d62f15"),
                            SubmissionDate = new DateTime(2024, 10, 7, 15, 35, 31, 51, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.codiva.io/p/dbc162b6-5afe-46bf-b4b3-ee42f11c37c3",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("e0d30fd2-1027-4af3-be3b-238a579dacb8"),
                            AssignmentId = new Guid("ac85b4e5-33ea-4d2c-a281-f7ec41da15f7"),
                            Compiler = 0,
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("9b934e06-3abd-4b8d-b45f-7e2106b4bc74"),
                            SubmissionDate = new DateTime(2024, 10, 7, 15, 36, 31, 51, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.codiva.io/p/e0f1785e-40a2-4174-a00d-e76fbcfc95f8",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("31edb16a-feb4-4cab-812c-e8a4bdb6ad45"),
                            AssignmentId = new Guid("ac85b4e5-33ea-4d2c-a281-f7ec41da15f7"),
                            Compiler = 0,
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("239e66d0-16c3-4ce4-b321-058b64269f5e"),
                            SubmissionDate = new DateTime(2024, 10, 7, 15, 55, 31, 51, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.codiva.io/p/925bfea6-e307-4cbb-8e43-dbf634ec7325",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("6252ac2f-e197-4ec3-821f-56ef3dffc72c"),
                            AssignmentId = new Guid("ac85b4e5-33ea-4d2c-a281-f7ec41da15f7"),
                            Compiler = 0,
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("e7c43279-2bcc-4c09-9165-b824041166fc"),
                            SubmissionDate = new DateTime(2024, 10, 7, 15, 15, 31, 51, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.codiva.io/p/dbc162b6-5afe-46bf-b4b3-ee42f11c37c4",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("7d0f9c15-9e1b-4301-8b6e-7812cca1d451"),
                            AssignmentId = new Guid("025f1811-79ec-43b2-9693-652fa2f7bdb1"),
                            Compiler = 1,
                            CreatedAt = new DateTime(2024, 11, 18, 0, 27, 21, 610, DateTimeKind.Utc).AddTicks(5890),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("8d676dc9-1a50-48f6-aa83-cb47535c5af3"),
                            SubmissionDate = new DateTime(2024, 11, 18, 0, 12, 19, 911, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.onlinegdb.com/cky2lPU84",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("7397a9ce-94a9-4e5b-9cbb-215f061b197e"),
                            AssignmentId = new Guid("025f1811-79ec-43b2-9693-652fa2f7bdb1"),
                            Compiler = 1,
                            CreatedAt = new DateTime(2024, 11, 18, 1, 28, 27, 708, DateTimeKind.Utc).AddTicks(3710),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("38141a4f-bc22-4514-8f9b-139a11b004b8"),
                            SubmissionDate = new DateTime(2024, 11, 18, 1, 27, 14, 246, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.onlinegdb.com/zWDNPiT9M",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("14cabe76-3398-4429-ad34-01679f08acb9"),
                            AssignmentId = new Guid("025f1811-79ec-43b2-9693-652fa2f7bdb1"),
                            Compiler = 1,
                            CreatedAt = new DateTime(2024, 11, 18, 14, 35, 49, 879, DateTimeKind.Utc).AddTicks(1230),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("9b934e06-3abd-4b8d-b45f-7e2106b4bc74"),
                            SubmissionDate = new DateTime(2024, 11, 18, 14, 28, 25, 801, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.onlinegdb.com/bdoucGuWb",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("fe8eb5ea-7686-4539-b13b-51bf931d36bb"),
                            AssignmentId = new Guid("025f1811-79ec-43b2-9693-652fa2f7bdb1"),
                            Compiler = 0,
                            CreatedAt = new DateTime(2024, 11, 18, 18, 3, 38, 659, DateTimeKind.Utc).AddTicks(3250),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("12bedd1a-d7c6-4b54-aeb5-507ef12d4f83"),
                            SubmissionDate = new DateTime(2024, 11, 18, 14, 28, 25, 801, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://www.codiva.io/p/cf89e5a1-d528-4334-b973-9fcacfbc28d6",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("d00b5731-977d-41cf-b8bf-7f693cb8d97b"),
                            AssignmentId = new Guid("e4be8d12-8d5e-43d2-817c-b5987043404d"),
                            Compiler = 1,
                            CreatedAt = new DateTime(2024, 11, 18, 18, 30, 52, 604, DateTimeKind.Utc).AddTicks(8630),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("38141a4f-bc22-4514-8f9b-139a11b004b2"),
                            SubmissionDate = new DateTime(2024, 11, 18, 14, 27, 25, 801, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://onlinegdb.com/lgantTSY2",
                            UrlState = 3
                        },
                        new
                        {
                            Id = new Guid("22e13d14-0349-49df-9fc9-ff6c9bbb4bd8"),
                            AssignmentId = new Guid("e4be8d12-8d5e-43d2-817c-b5987043404d"),
                            Compiler = 1,
                            CreatedAt = new DateTime(2024, 11, 18, 18, 46, 4, 173, DateTimeKind.Utc).AddTicks(5290),
                            Grade = 0.0,
                            IsEnabled = true,
                            StudentId = new Guid("8d676dc9-1a50-48f6-aa83-cb47535c5af3"),
                            SubmissionDate = new DateTime(2024, 11, 18, 14, 22, 25, 801, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Url = "https://onlinegdb.com/EsUiHpxUO",
                            UrlState = 3
                        });
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("LogInAttempts")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("ResetPasswordAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UnlockDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VerificationCode")
                        .HasColumnType("integer");

                    b.Property<DateTime>("VerificationCodeExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", "plagi_tracker");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Student", b =>
                {
                    b.HasBaseType("PlagiTracker.Data.Entities.User");

                    b.ToTable("Students", "plagi_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38141a4f-bc22-4514-8f9b-139a11b004b8"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bschweinsteiger@plagitracker.com",
                            FirstName = "Bastian",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Schweinsteiger",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 10000000,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("38141a4f-bc22-4514-8f9b-139a11b004b2"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "apoulsen@plagitracker.com",
                            FirstName = "Aron",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Poulsen",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 10000000,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("a37b3252-3e54-4199-8c4b-728238fc76b8"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dprivat@plagitracker.com",
                            FirstName = "Daoblur",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Privat",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 10000000,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("8d676dc9-1a50-48f6-aa83-cb47535c5af3"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eprocke@plagitracker.com",
                            FirstName = "Elmersson",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Procke",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("af2eff91-54b0-43b4-91c4-57b7e2d62f15"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "rkadyrov@plagitracker.com",
                            FirstName = "Ramzan",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Kadyrov",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("e7c43279-2bcc-4c09-9165-b824041166fc"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "avonkageneck@plagitracker.com",
                            FirstName = "August",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "von Kageneck",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("12bedd1a-d7c6-4b54-aeb5-507ef12d4f83"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "btennyson@plagitracker.com",
                            FirstName = "Ben",
                            IsEnabled = true,
                            IsLocked = true,
                            IsVerified = false,
                            LastName = "Tennyson",
                            LogInAttempts = 3,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(2024, 10, 27, 10, 50, 1, 462, DateTimeKind.Utc).AddTicks(3040),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("239e66d0-16c3-4ce4-b321-058b64269f5e"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "kkvaratskhelia@plagitracker.com",
                            FirstName = "Khvicha",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Kvaratskhelia",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("9b934e06-3abd-4b8d-b45f-7e2106b4bc74"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "knurmagomedov@plagitracker.com",
                            FirstName = "Khabib",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Nurmagomedov",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("1979d2a7-de35-4d83-9aa9-857171cba7fa"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ptorres@plagitracker.com",
                            FirstName = "Pedro",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Torres",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Teacher", b =>
                {
                    b.HasBaseType("PlagiTracker.Data.Entities.User");

                    b.ToTable("Teachers", "plagi_tracker");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5500125e-16f5-4b77-9220-cc4dab69c102"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "pillanes@plagitracker.com",
                            FirstName = "Pablo",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Illanes",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("0392d24c-a1f5-4022-8278-cfa4efb14b8c"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lkennedy@plagitracker.com",
                            FirstName = "Luis",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Kennedy",
                            LogInAttempts = 2,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216, 175, 220, 117, 12, 253, 183, 88, 119, 47, 192, 90, 98, 73, 23, 199, 108 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(2024, 10, 8, 0, 53, 2, 247, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 0,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("aa597a6c-b219-4743-b5c6-8740551e79e0"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alaghari@plagitracker.com",
                            FirstName = "Anas",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Laghari",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 10000000,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("865bf0cc-1fe7-4203-944e-f353540d7210"),
                            CreatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            Email = "lriquelme@plagitracker.com",
                            FirstName = "Luis Enrique",
                            IsEnabled = true,
                            IsLocked = false,
                            IsVerified = false,
                            LastName = "Riquelme",
                            LogInAttempts = 0,
                            PasswordHash = new byte[] { 94, 136, 72, 152, 218, 40, 4, 113, 81, 208, 229, 111, 141, 198, 41, 39, 115, 96, 61, 13, 106, 171, 189, 214, 42, 17, 239, 114, 29, 21, 66, 216 },
                            ResetPasswordAttempts = 0,
                            UnlockDate = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            UpdatedAt = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc),
                            VerificationCode = 10000000,
                            VerificationCodeExpiration = new DateTime(1, 1, 1, 5, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Assignment", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Class", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlagiTracker.Data.Entities.Class", "ParentClass")
                        .WithMany()
                        .HasForeignKey("ParentClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("ParentClass");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Code", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Submission", "Submission")
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Course", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Enrollment", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlagiTracker.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Exercise", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Method", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Parameter", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Method", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Plagiarism", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Code", "Code")
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Code");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Submission", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PlagiTracker.Data.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Student", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("PlagiTracker.Data.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlagiTracker.Data.Entities.Teacher", b =>
                {
                    b.HasOne("PlagiTracker.Data.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("PlagiTracker.Data.Entities.Teacher", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
